workflows:
  default-workflow:
    name: Default Workflow
    environment:
      flutter: stable  # Choose the Flutter version (e.g., stable, beta)
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ios --release
      - name: Build Android
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
